name: Fast-forward
description: Fast-forward merge a pull request.

inputs:
  github_token:
    description: GitHub Actions token.
    default: ${{ github.token }}

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Fast-forward
      id: fast-forward
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        PYTHONUNBUFFERED: "1"
        PYTHONDONTWRITEBYTECODE: "1"
        PYTHONFAULTHANDLER: "1"
        PYTHONENCODING: "utf-8"
      run: python ${{ github.action_path }}/main.py
      shell: bash
