name: Fast-forward

on:
  issue_comment:
    types:
      - created
      - edited

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Allows merging the PR.
      pull-requests: write  # Writing comments on PRs.
      issues: write  # Also required for posting comments on PRs.

    steps:
      - uses: MrThearMan/sandbox@main
