name: Fast-forward

on:
  issue_comment:
    types:
      - created
      - edited

jobs:
  fast-forward:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Allows merging the PR.
      pull-requests: write  # Writing comments on PRs.
      issues: write  # Also required for posting comments on PRs.

    steps:
      - name: Fast-forward merge
        uses: MrThearMan/sandbox@main
