name: Fast-forward

on:
  issue_comment:
    types:
      - created
      - edited

jobs:
  fast-forward:

    name: Fast-forward
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Allows merging the PR.
      pull-requests: write  # Writing comments on PRs.
      issues: write  # Also required for posting comments on PRs.

    # Only run if the comment is one of the defined keywords.
    if: >-
      ${{
        github.event.issue.pull_request
        && contains(fromJSON('["/fast-forward", "/ff"]'), github.event.comment.body)
      }}

    steps:
      - name: Fast-forward
        uses: MrThearMan/prff@v1
