name: Fast-forward merge pull request

on:
  workflow_call:

jobs:
  test:
    name: Fast-forward merge pull request
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Fast-forward
        id: fast-forward
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PYTHONUNBUFFERED: "1"
          PYTHONDONTWRITEBYTECODE: "1"
          PYTHONFAULTHANDLER: "1"
          PYTHONENCODING: "utf-8"
        run: |
          python ${{ github.workspace }}/fast_forward.py \
            --event-path '${{ github.event_path }}'
        shell: bash
